name: Release DevShare

on:
    push:
        tags:
        - 'v*'

jobs:
  goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install mingw-w64 (for windres)
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: v2.9.0
          args: release --clean --config=.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}